import type { MatchResult } from "./types";

const WIDTH = 600;
const HEIGHT = 500;
const MARGIN = 40;

function loadImage(src: string): Promise<HTMLImageElement> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.crossOrigin = "anonymous";
    img.onload = () => resolve(img);
    img.onerror = reject;
    img.src = src;
  });
}

export async function renderMatchCard(
  nameA: string,
  nameB: string,
  result: MatchResult,
  photoA?: string | null,
  photoB?: string | null,
): Promise<Blob> {
  const canvas = document.createElement("canvas");
  canvas.width = WIDTH;
  canvas.height = HEIGHT;
  const ctx = canvas.getContext("2d")!;

  ctx.fillStyle = "#050505";
  ctx.fillRect(0, 0, WIDTH, HEIGHT);

  ctx.strokeStyle = "rgba(255,255,255,0.1)";
  ctx.lineWidth = 1;
  ctx.strokeRect(2, 2, WIDTH - 4, HEIGHT - 4);

  const photoSize = 72;
  const photoY = 60;
  const leftX = WIDTH / 2 - photoSize - 50;
  const rightX = WIDTH / 2 + 50;

  const imgA = photoA ? await loadImage(photoA).catch(() => null) : null;
  const imgB = photoB ? await loadImage(photoB).catch(() => null) : null;

  if (imgA) {
    ctx.save();
    ctx.beginPath();
    ctx.arc(leftX + photoSize / 2, photoY + photoSize / 2, photoSize / 2, 0, Math.PI * 2);
    ctx.closePath();
    ctx.clip();
    ctx.drawImage(imgA, leftX, photoY, photoSize, photoSize);
    ctx.restore();
  } else {
    ctx.save();
    ctx.beginPath();
    ctx.arc(leftX + photoSize / 2, photoY + photoSize / 2, photoSize / 2, 0, Math.PI * 2);
    ctx.closePath();
    ctx.strokeStyle = "rgba(255,255,255,0.2)";
    ctx.lineWidth = 1;
    ctx.stroke();
    ctx.fillStyle = "rgba(255,255,255,0.05)";
    ctx.fill();
    ctx.fillStyle = "rgba(255,255,255,0.3)";
    ctx.font = "28px monospace";
    ctx.textAlign = "center";
    ctx.textBaseline = "middle";
    ctx.fillText("?", leftX + photoSize / 2, photoY + photoSize / 2);
    ctx.restore();
  }

  if (imgB) {
    ctx.save();
    ctx.beginPath();
    ctx.arc(rightX + photoSize / 2, photoY + photoSize / 2, photoSize / 2, 0, Math.PI * 2);
    ctx.closePath();
    ctx.clip();
    ctx.drawImage(imgB, rightX, photoY, photoSize, photoSize);
    ctx.restore();
  } else {
    ctx.save();
    ctx.beginPath();
    ctx.arc(rightX + photoSize / 2, photoY + photoSize / 2, photoSize / 2, 0, Math.PI * 2);
    ctx.closePath();
    ctx.strokeStyle = "rgba(255,255,255,0.2)";
    ctx.lineWidth = 1;
    ctx.stroke();
    ctx.fillStyle = "rgba(255,255,255,0.05)";
    ctx.fill();
    ctx.fillStyle = "rgba(255,255,255,0.3)";
    ctx.font = "28px monospace";
    ctx.textAlign = "center";
    ctx.textBaseline = "middle";
    ctx.fillText("?", rightX + photoSize / 2, photoY + photoSize / 2);
    ctx.restore();
  }

  ctx.fillStyle = "rgba(255,255,255,0.8)";
  ctx.font = "16px monospace";
  ctx.textAlign = "center";
  ctx.textBaseline = "top";
  ctx.fillText(nameA.toUpperCase(), leftX + photoSize / 2, photoY + photoSize + 12);
  ctx.fillText(nameB.toUpperCase(), rightX + photoSize / 2, photoY + photoSize + 12);

  ctx.fillStyle = "rgba(255,255,255,0.2)";
  ctx.font = "24px monospace";
  ctx.textBaseline = "middle";
  ctx.fillText("✦", WIDTH / 2, photoY + photoSize / 2);

  const scoreY = photoY + photoSize + 60;
  ctx.fillStyle = "rgba(255,255,255,0.15)";
  ctx.font = "12px monospace";
  ctx.textBaseline = "bottom";
  ctx.fillText("MATCH", WIDTH / 2, scoreY);

  const scoreSize = result.score >= 90 ? 72 : 64;
  ctx.fillStyle = "rgba(255,255,255,0.9)";
  ctx.font = "bold ${scoreSize}px monospace";
  ctx.textBaseline = "top";
  ctx.fillText(`${result.score}%`, WIDTH / 2, scoreY + 4);

  const tagY = scoreY + scoreSize + 20;
  ctx.fillStyle = "rgba(255,255,255,0.4)";
  ctx.font = "11px monospace";
  ctx.textBaseline = "top";
  ctx.fillText(result.tagline.toUpperCase(), WIDTH / 2, tagY);

  const barY = tagY + 40;
  const barMaxWidth = 340;
  const barLeft = (WIDTH - barMaxWidth) / 2;
  const barH = 14;
  const barGap = 24;

  ctx.textBaseline = "middle";
  result.subScores.forEach((s, i) => {
    const y = barY + i * barGap;

    ctx.fillStyle = "rgba(255,255,255,0.5)";
    ctx.font = "9px monospace";
    ctx.textAlign = "left";
    ctx.fillText(s.label.toUpperCase(), barLeft, y);

    ctx.fillStyle = "rgba(255,255,255,0.06)";
    ctx.fillRect(barLeft, y + 8, barMaxWidth, barH - 8);

    const fillW = (s.value / 100) * barMaxWidth;
    ctx.fillStyle = "rgba(255,255,255,0.3)";
    ctx.fillRect(barLeft, y + 8, fillW, barH - 8);

    ctx.fillStyle = "rgba(255,255,255,0.5)";
    ctx.font = "9px monospace";
    ctx.textAlign = "right";
    ctx.fillText(`${s.value}%`, WIDTH - barLeft, y);
  });

  ctx.fillStyle = "rgba(255,255,255,0.15)";
  ctx.font = "8px monospace";
  ctx.textAlign = "center";
  ctx.textBaseline = "bottom";
  ctx.fillText(
    `generated by runen — ${result.algorithm}`,
    WIDTH / 2,
    HEIGHT - MARGIN / 2,
  );

  return new Promise((resolve, reject) => {
    canvas.toBlob((blob) => {
      if (blob) resolve(blob);
      else reject(new Error("canvas toBlob failed"));
    }, "image/png");
  });
}
